export const stadiumBase = [
	{
		id: 1,
		name: 'Lumen Field',
		fifaName: 'Seattle Stadium',
		capacity: 66925,
		city: 'Seattle',
		stateProvince: 'WA',
		country: 'USA',
		metroName: 'Seattle-Tacoma-Bellevue MSA',
		lon: -122.332245,
		lat: 47.595097,
		img: 'transit-oriented-stadiums/seattle.png',
	},
	{
		id: 2,
		name: "Levi's Stadium",
		fifaName: 'San Francisco Bay Area Stadium',
		capacity: 68827,
		city: 'Santa Clara',
		stateProvince: 'CA',
		country: 'USA',
		metroName: 'San Jose-Sunnyvale-Santa Clara MSA',
		lon: -121.969688,
		lat: 37.403263,
		img: 'transit-oriented-stadiums/santa-clara.png',
	},
	{
		id: 3,
		name: 'SoFi Stadium',
		fifaName: 'Los Angeles Stadium',
		capacity: 70492,
		city: 'Inglewood',
		stateProvince: 'CA',
		country: 'USA',
		metroName: 'Los Angeles-Long Beach-Anaheim MSA',
		lon: -118.33963,
		lat: 33.953587,
		img: 'transit-oriented-stadiums/inglewood.png',
	},
	{
		id: 4,
		name: 'Arrowhead Stadium',
		fifaName: 'Kansas City Stadium',
		capacity: 69045,
		city: 'Kansas City',
		stateProvince: 'MO',
		country: 'USA',
		metroName: 'Kansas City MSA',
		lon: -94.484566,
		lat: 39.048786,
		img: 'transit-oriented-stadiums/kansas-city.png',
	},
	{
		id: 5,
		name: 'Gillette Stadium',
		fifaName: 'Boston Stadium',
		capacity: 64146,
		city: 'Foxborough',
		stateProvince: 'MA',
		country: 'USA',
		metroName: 'Boston-Cambridge-Newton MSA',
		lon: -71.264709,
		lat: 42.090908,
		img: 'transit-oriented-stadiums/boston.png',
	},
	{
		id: 6,
		name: 'Lincoln Financial Field',
		fifaName: 'Philadelphia Stadium',
		capacity: 68324,
		city: 'Philadelphia',
		stateProvince: 'PA',
		country: 'USA',
		metroName: 'Philadelphia-Camden-Wilmington MSA',
		lon: -75.168098,
		lat: 39.900898,
		img: 'transit-oriented-stadiums/philly.png',
	},
	{
		id: 7,
		name: 'Mercedes-Benz Stadium',
		fifaName: 'Atlanta Stadium',
		capacity: 68239,
		city: 'Atlanta',
		stateProvince: 'GA',
		country: 'USA',
		metroName: 'Atlanta-Sandy Springs-Roswell MSA',
		lon: -84.401993,
		lat: 33.755489,
		img: 'transit-oriented-stadiums/atlanta.png',
	},
	{
		id: 8,
		name: 'AT&T Stadium',
		fifaName: 'Dallas Stadium',
		capacity: 70649,
		city: 'Arlington',
		stateProvince: 'TX',
		country: 'USA',
		metroName: 'Dallas-Fort Worth-Arlington MSA',
		lon: -97.093628,
		lat: 32.747841,
		img: 'transit-oriented-stadiums/dallas.png',
	},
	{
		id: 9,
		name: 'NRG Stadium',
		fifaName: 'Houston Stadium',
		capacity: 68777,
		city: 'Houston',
		stateProvince: 'TX',
		country: 'USA',
		metroName: 'Houston-The Woodlands-Sugar Land MSA',
		lon: -95.411667,
		lat: 29.68486,
		img: 'transit-oriented-stadiums/houston.png',
	},
	{
		id: 10,
		name: 'Hard Rock Stadium',
		fifaName: 'Miami Stadium',
		capacity: 64478,
		city: 'Miami Gardens',
		stateProvince: 'FL',
		country: 'USA',
		metroName: 'Miami-Fort Lauderdale-West Palm Beach MSA',
		lon: -80.239311,
		lat: 25.95796,
		img: 'transit-oriented-stadiums/miami.png',
	},
	{
		id: 11,
		name: 'MetLife Stadium',
		fifaName: 'New York New Jersey Stadium',
		capacity: 80663,
		city: 'East Rutherford',
		stateProvince: 'NJ',
		country: 'USA',
		metroName: 'New York-Newark-Jersey City MSA',
		lon: -74.072503,
		lat: 40.81283,
		img: 'transit-oriented-stadiums/new-york.png',
	},
	{
		id: 12,
		name: 'Estadio Azteca',
		fifaName: 'Mexico City Stadium',
		capacity: 80824,
		city: 'Mexico City',
		stateProvince: 'CDMX',
		country: 'MEX',
		metroName: 'Zona Metropolitana de la Ciudad de México',
		lon: -99.147709,
		lat: 19.301696,
		img: 'transit-oriented-stadiums/mexico-city.png',
	},
	{
		id: 14,
		name: 'Estadio Akron',
		fifaName: 'Estadio Guadalajara',
		capacity: 45664,
		city: 'Zapopan',
		stateProvince: 'JAL',
		country: 'MEX',
		metroName: 'Zona Metropolitana de Guadalajara',
		lon: -103.4628,
		lat: 20.6817,
		img: 'transit-oriented-stadiums/guadalajara.png',
	},
	{
		id: 15,
		name: 'BMO Field',
		fifaName: 'Toronto Stadium',
		capacity: 43036,
		city: 'Toronto',
		stateProvince: 'ON',
		country: 'CAN',
		metroName: 'Toronto Census Metropolitan Area',
		lon: -79.418617,
		lat: 43.633335,
		img: 'transit-oriented-stadiums/toronto.png',
	},
	{
		id: 16,
		name: 'BC Place',
		fifaName: 'BC Place Vancouver',
		capacity: 52497,
		city: 'Vancouver',
		stateProvince: 'BC',
		country: 'CAN',
		metroName: 'Vancouver Census Metropolitan Area',
		lon: -123.112404,
		lat: 49.276684,
		img: 'transit-oriented-stadiums/vancouver.png',
	},
];
